/*
 * This file has been auto-generated by ProviderOne
 *
 * Copyright (C) 2011 GroupMe, Inc.
 */
package com.groupme.providerone.sample.database.autogen.tables;


import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;

import com.groupme.providerone.sample.database.SampleProvider;
import com.groupme.providerone.sample.database.autogen.PersistentObject;
import com.groupme.providerone.sample.database.tables.MyViewInfo;

public class BaseMyViewInfo  {

    public interface Columns {
		String _ID = "_id";
		String MY_BOOLEAN = "my_boolean";
		String MY_STRING = "my_string";

    }

    public static final String TABLE_NAME = "my_view";
    public static final String SQL_CREATE = "CREATE VIEW \"my_view\" AS  	SELECT \"_id\", \"my_boolean\", \"my_string\" FROM \"my_table\"";
    public static final String SQL_DROP = "DROP VIEW IF EXISTS \"my_view\"";

    public static final String[] ALL_COLUMNS = new String[] {
		Columns._ID,
		Columns.MY_BOOLEAN,
		Columns.MY_STRING,

    };

    public static final MyViewInfo.ColumnHelper ALL_COLUMNS_HELPER = new MyViewInfo.ColumnHelper(ALL_COLUMNS);


    public static final String PATH = "my_view";
    public static final String CONTENT_TYPE = "vnd.android.cursor.dir/com.groupme.providerone.sample.my_view";
    public static final String CONTENT_ITEM_TYPE = "vnd.android.cursor.item/com.groupme.providerone.sample.my_view";
    public static final Uri CONTENT_URI = Uri.withAppendedPath(SampleProvider.getBaseContentUri(), PATH);
    public static final Uri COUNT_URI = Uri.withAppendedPath(CONTENT_URI, SampleProvider.RAW_PATH_COUNT);
    public static final Uri SUM_URI = Uri.withAppendedPath(CONTENT_URI, SampleProvider.RAW_PATH_SUM);
    public static final Uri ID_LOOKUP_URI = Uri.withAppendedPath(CONTENT_URI, SampleProvider.RAW_PATH_ID);



    public static final int INSERT_ALGORITHM = SQLiteDatabase.CONFLICT_NONE;
    public static final int UPDATE_ALGORITHM = SQLiteDatabase.CONFLICT_NONE;

    public static void createTable(SQLiteDatabase db) {
        db.execSQL(SQL_DROP);
        db.execSQL(SQL_CREATE);
    }

    public static void upgradeTable(SQLiteDatabase db, int oldVersion, int newVersion) {
		createTable(db);
    }

    public static Uri buildIdLookupUri(long _id) {
        return Uri.withAppendedPath(ID_LOOKUP_URI, Uri.encode(String.valueOf(_id)));
    }



    public static class ColumnHelper extends PersistentObject.ColumnHelper {
		public int col__id = -1;
		public int col_my_boolean = -1;
		public int col_my_string = -1;


		public ColumnHelper(String[] projection) {
			super(projection);
			col__id = getColumnIndex(Columns._ID);
			col_my_boolean = getColumnIndex(Columns.MY_BOOLEAN);
			col_my_string = getColumnIndex(Columns.MY_STRING);
		}
    }




    public static final Uri LOOKUP_URI = Uri.withAppendedPath(CONTENT_URI, SampleProvider.RAW_PATH_LOOKUP);
    public static Uri buildMyStringLookupUri(String myString) {
        return Uri.withAppendedPath(LOOKUP_URI, Uri.encode(myString));
    }

}
